# Generated by Django 5.1.4 on 2025-01-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='imagerrr',
        ),
    ]
