# Generated by Django 5.1.4 on 2025-01-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_image_post_imagerrr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagerrr',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
